---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickstart-se-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickstart-se
  template:
    metadata:
      labels:
        app: quickstart-se
    spec:
      containers:
      - name: quickstart-se
        image: phx.ocir.io/oraclegermanpab/helidon-quickstart-se:latest
        ports:
        - name: quickstart-se
          containerPort: 8090
          protocol: TCP
      imagePullSecrets:
      - name: ocirsecret

---
apiVersion: v1
kind: Service
metadata:
  name: quickstart-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 100Mbps
  labels:
    app: quickstart-se
spec:
  type: LoadBalancer
  selector:
    app: quickstart-se
  ports:
  - port: 80
    protocol: TCP
      targetPort: 8090